# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/polter/workspace/yay

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/polter/workspace/yay

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/polter/workspace/yay/CMakeFiles /home/polter/workspace/yay/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/polter/workspace/yay/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named yay

# Build rule for target.
yay: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yay
.PHONY : yay

# fast build rule for target.
yay/fast:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/build
.PHONY : yay/fast

#=============================================================================
# Target rules for targets named yay_static

# Build rule for target.
yay_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yay_static
.PHONY : yay_static

# fast build rule for target.
yay_static/fast:
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/build
.PHONY : yay_static/fast

src/yay_cmdproc.o: src/yay_cmdproc.cpp.o
.PHONY : src/yay_cmdproc.o

# target to build an object file
src/yay_cmdproc.cpp.o:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_cmdproc.cpp.o
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_cmdproc.cpp.o
.PHONY : src/yay_cmdproc.cpp.o

src/yay_cmdproc.i: src/yay_cmdproc.cpp.i
.PHONY : src/yay_cmdproc.i

# target to preprocess a source file
src/yay_cmdproc.cpp.i:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_cmdproc.cpp.i
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_cmdproc.cpp.i
.PHONY : src/yay_cmdproc.cpp.i

src/yay_cmdproc.s: src/yay_cmdproc.cpp.s
.PHONY : src/yay_cmdproc.s

# target to generate assembly for a file
src/yay_cmdproc.cpp.s:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_cmdproc.cpp.s
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_cmdproc.cpp.s
.PHONY : src/yay_cmdproc.cpp.s

src/yay_geo.o: src/yay_geo.cpp.o
.PHONY : src/yay_geo.o

# target to build an object file
src/yay_geo.cpp.o:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_geo.cpp.o
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_geo.cpp.o
.PHONY : src/yay_geo.cpp.o

src/yay_geo.i: src/yay_geo.cpp.i
.PHONY : src/yay_geo.i

# target to preprocess a source file
src/yay_geo.cpp.i:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_geo.cpp.i
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_geo.cpp.i
.PHONY : src/yay_geo.cpp.i

src/yay_geo.s: src/yay_geo.cpp.s
.PHONY : src/yay_geo.s

# target to generate assembly for a file
src/yay_geo.cpp.s:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_geo.cpp.s
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_geo.cpp.s
.PHONY : src/yay_geo.cpp.s

src/yay_keymaps.o: src/yay_keymaps.cpp.o
.PHONY : src/yay_keymaps.o

# target to build an object file
src/yay_keymaps.cpp.o:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_keymaps.cpp.o
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_keymaps.cpp.o
.PHONY : src/yay_keymaps.cpp.o

src/yay_keymaps.i: src/yay_keymaps.cpp.i
.PHONY : src/yay_keymaps.i

# target to preprocess a source file
src/yay_keymaps.cpp.i:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_keymaps.cpp.i
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_keymaps.cpp.i
.PHONY : src/yay_keymaps.cpp.i

src/yay_keymaps.s: src/yay_keymaps.cpp.s
.PHONY : src/yay_keymaps.s

# target to generate assembly for a file
src/yay_keymaps.cpp.s:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_keymaps.cpp.s
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_keymaps.cpp.s
.PHONY : src/yay_keymaps.cpp.s

src/yay_logger.o: src/yay_logger.cpp.o
.PHONY : src/yay_logger.o

# target to build an object file
src/yay_logger.cpp.o:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_logger.cpp.o
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_logger.cpp.o
.PHONY : src/yay_logger.cpp.o

src/yay_logger.i: src/yay_logger.cpp.i
.PHONY : src/yay_logger.i

# target to preprocess a source file
src/yay_logger.cpp.i:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_logger.cpp.i
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_logger.cpp.i
.PHONY : src/yay_logger.cpp.i

src/yay_logger.s: src/yay_logger.cpp.s
.PHONY : src/yay_logger.s

# target to generate assembly for a file
src/yay_logger.cpp.s:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_logger.cpp.s
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_logger.cpp.s
.PHONY : src/yay_logger.cpp.s

src/yay_ngrams.o: src/yay_ngrams.cpp.o
.PHONY : src/yay_ngrams.o

# target to build an object file
src/yay_ngrams.cpp.o:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_ngrams.cpp.o
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_ngrams.cpp.o
.PHONY : src/yay_ngrams.cpp.o

src/yay_ngrams.i: src/yay_ngrams.cpp.i
.PHONY : src/yay_ngrams.i

# target to preprocess a source file
src/yay_ngrams.cpp.i:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_ngrams.cpp.i
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_ngrams.cpp.i
.PHONY : src/yay_ngrams.cpp.i

src/yay_ngrams.s: src/yay_ngrams.cpp.s
.PHONY : src/yay_ngrams.s

# target to generate assembly for a file
src/yay_ngrams.cpp.s:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_ngrams.cpp.s
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_ngrams.cpp.s
.PHONY : src/yay_ngrams.cpp.s

src/yay_shell.o: src/yay_shell.cpp.o
.PHONY : src/yay_shell.o

# target to build an object file
src/yay_shell.cpp.o:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_shell.cpp.o
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_shell.cpp.o
.PHONY : src/yay_shell.cpp.o

src/yay_shell.i: src/yay_shell.cpp.i
.PHONY : src/yay_shell.i

# target to preprocess a source file
src/yay_shell.cpp.i:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_shell.cpp.i
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_shell.cpp.i
.PHONY : src/yay_shell.cpp.i

src/yay_shell.s: src/yay_shell.cpp.s
.PHONY : src/yay_shell.s

# target to generate assembly for a file
src/yay_shell.cpp.s:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_shell.cpp.s
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_shell.cpp.s
.PHONY : src/yay_shell.cpp.s

src/yay_string_pool.o: src/yay_string_pool.cpp.o
.PHONY : src/yay_string_pool.o

# target to build an object file
src/yay_string_pool.cpp.o:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_string_pool.cpp.o
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_string_pool.cpp.o
.PHONY : src/yay_string_pool.cpp.o

src/yay_string_pool.i: src/yay_string_pool.cpp.i
.PHONY : src/yay_string_pool.i

# target to preprocess a source file
src/yay_string_pool.cpp.i:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_string_pool.cpp.i
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_string_pool.cpp.i
.PHONY : src/yay_string_pool.cpp.i

src/yay_string_pool.s: src/yay_string_pool.cpp.s
.PHONY : src/yay_string_pool.s

# target to generate assembly for a file
src/yay_string_pool.cpp.s:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_string_pool.cpp.s
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_string_pool.cpp.s
.PHONY : src/yay_string_pool.cpp.s

src/yay_translit_ru.o: src/yay_translit_ru.cpp.o
.PHONY : src/yay_translit_ru.o

# target to build an object file
src/yay_translit_ru.cpp.o:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_translit_ru.cpp.o
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_translit_ru.cpp.o
.PHONY : src/yay_translit_ru.cpp.o

src/yay_translit_ru.i: src/yay_translit_ru.cpp.i
.PHONY : src/yay_translit_ru.i

# target to preprocess a source file
src/yay_translit_ru.cpp.i:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_translit_ru.cpp.i
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_translit_ru.cpp.i
.PHONY : src/yay_translit_ru.cpp.i

src/yay_translit_ru.s: src/yay_translit_ru.cpp.s
.PHONY : src/yay_translit_ru.s

# target to generate assembly for a file
src/yay_translit_ru.cpp.s:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_translit_ru.cpp.s
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_translit_ru.cpp.s
.PHONY : src/yay_translit_ru.cpp.s

src/yay_utf8.o: src/yay_utf8.cpp.o
.PHONY : src/yay_utf8.o

# target to build an object file
src/yay_utf8.cpp.o:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_utf8.cpp.o
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_utf8.cpp.o
.PHONY : src/yay_utf8.cpp.o

src/yay_utf8.i: src/yay_utf8.cpp.i
.PHONY : src/yay_utf8.i

# target to preprocess a source file
src/yay_utf8.cpp.i:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_utf8.cpp.i
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_utf8.cpp.i
.PHONY : src/yay_utf8.cpp.i

src/yay_utf8.s: src/yay_utf8.cpp.s
.PHONY : src/yay_utf8.s

# target to generate assembly for a file
src/yay_utf8.cpp.s:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_utf8.cpp.s
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_utf8.cpp.s
.PHONY : src/yay_utf8.cpp.s

src/yay_util.o: src/yay_util.cpp.o
.PHONY : src/yay_util.o

# target to build an object file
src/yay_util.cpp.o:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_util.cpp.o
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_util.cpp.o
.PHONY : src/yay_util.cpp.o

src/yay_util.i: src/yay_util.cpp.i
.PHONY : src/yay_util.i

# target to preprocess a source file
src/yay_util.cpp.i:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_util.cpp.i
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_util.cpp.i
.PHONY : src/yay_util.cpp.i

src/yay_util.s: src/yay_util.cpp.s
.PHONY : src/yay_util.s

# target to generate assembly for a file
src/yay_util.cpp.s:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_util.cpp.s
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_util.cpp.s
.PHONY : src/yay_util.cpp.s

src/yay_util_time.o: src/yay_util_time.cpp.o
.PHONY : src/yay_util_time.o

# target to build an object file
src/yay_util_time.cpp.o:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_util_time.cpp.o
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_util_time.cpp.o
.PHONY : src/yay_util_time.cpp.o

src/yay_util_time.i: src/yay_util_time.cpp.i
.PHONY : src/yay_util_time.i

# target to preprocess a source file
src/yay_util_time.cpp.i:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_util_time.cpp.i
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_util_time.cpp.i
.PHONY : src/yay_util_time.cpp.i

src/yay_util_time.s: src/yay_util_time.cpp.s
.PHONY : src/yay_util_time.s

# target to generate assembly for a file
src/yay_util_time.cpp.s:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_util_time.cpp.s
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_util_time.cpp.s
.PHONY : src/yay_util_time.cpp.s

src/yay_xml_util.o: src/yay_xml_util.cpp.o
.PHONY : src/yay_xml_util.o

# target to build an object file
src/yay_xml_util.cpp.o:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_xml_util.cpp.o
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_xml_util.cpp.o
.PHONY : src/yay_xml_util.cpp.o

src/yay_xml_util.i: src/yay_xml_util.cpp.i
.PHONY : src/yay_xml_util.i

# target to preprocess a source file
src/yay_xml_util.cpp.i:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_xml_util.cpp.i
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_xml_util.cpp.i
.PHONY : src/yay_xml_util.cpp.i

src/yay_xml_util.s: src/yay_xml_util.cpp.s
.PHONY : src/yay_xml_util.s

# target to generate assembly for a file
src/yay_xml_util.cpp.s:
	$(MAKE) -f CMakeFiles/yay.dir/build.make CMakeFiles/yay.dir/src/yay_xml_util.cpp.s
	$(MAKE) -f CMakeFiles/yay_static.dir/build.make CMakeFiles/yay_static.dir/src/yay_xml_util.cpp.s
.PHONY : src/yay_xml_util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... yay"
	@echo "... yay_static"
	@echo "... src/yay_cmdproc.o"
	@echo "... src/yay_cmdproc.i"
	@echo "... src/yay_cmdproc.s"
	@echo "... src/yay_geo.o"
	@echo "... src/yay_geo.i"
	@echo "... src/yay_geo.s"
	@echo "... src/yay_keymaps.o"
	@echo "... src/yay_keymaps.i"
	@echo "... src/yay_keymaps.s"
	@echo "... src/yay_logger.o"
	@echo "... src/yay_logger.i"
	@echo "... src/yay_logger.s"
	@echo "... src/yay_ngrams.o"
	@echo "... src/yay_ngrams.i"
	@echo "... src/yay_ngrams.s"
	@echo "... src/yay_shell.o"
	@echo "... src/yay_shell.i"
	@echo "... src/yay_shell.s"
	@echo "... src/yay_string_pool.o"
	@echo "... src/yay_string_pool.i"
	@echo "... src/yay_string_pool.s"
	@echo "... src/yay_translit_ru.o"
	@echo "... src/yay_translit_ru.i"
	@echo "... src/yay_translit_ru.s"
	@echo "... src/yay_utf8.o"
	@echo "... src/yay_utf8.i"
	@echo "... src/yay_utf8.s"
	@echo "... src/yay_util.o"
	@echo "... src/yay_util.i"
	@echo "... src/yay_util.s"
	@echo "... src/yay_util_time.o"
	@echo "... src/yay_util_time.i"
	@echo "... src/yay_util_time.s"
	@echo "... src/yay_xml_util.o"
	@echo "... src/yay_xml_util.i"
	@echo "... src/yay_xml_util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

